import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useSpeechSynthesis } from 'react-speech-kit';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [value, setValue] = useState('');
  const { speak } = useSpeechSynthesis();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main >
        
        <div className="">
          <div className="text">
            <h2>Convert your Text Now</h2>
          </div>
          <div className="text-area">
            <textarea
              rows="10"
            
              value={value}
              onChange={(e) => setValue(e.target.value)}
            ></textarea>
          </div>
          <div className="button">
            <button onClick={() => speak({ text: value })}>Speak</button>
          </div>
        </div>
      </main>
    </>
  )
}
